spotless
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/.github/workflows/210-flow-merge-queue-controller.yaml b/.github/workflows/210-flow-merge-queue-controller.yaml
--- a/.github/workflows/210-flow-merge-queue-controller.yaml
+++ b/.github/workflows/210-flow-merge-queue-controller.yaml
@@ -50,10 +50,10 @@ jobs:
       slack-tck-report-webhook: ${{ secrets.SLACK_TCK_MONITOR_WEBHOOK }}
 
   # Trigger the MQ Performance/Longevity Tests
-#  trigger-merge-queue-performance-longevity-tests:
-#    name: Merge Queue Performance/Longevity Tests
-#    uses: ./.github/workflows/zxc-performance-tests.yaml
-#    Ensure we use ${{ vars.MQPT_CLUSTER }} to determine which cluster to run the tests on
+  #  trigger-merge-queue-performance-longevity-tests:
+  #    name: Merge Queue Performance/Longevity Tests
+  #    uses: ./.github/workflows/zxc-performance-tests.yaml
+  #    Ensure we use ${{ vars.MQPT_CLUSTER }} to determine which cluster to run the tests on
 
   # Update the variable `MQPT_CLUSTER` in Github
   # Options are: Dallas_n10, Dallas_n11, Dallas_n12
@@ -68,19 +68,19 @@ jobs:
 
       - name: Calculate Next Dallas Cluster Name
         run: |
-            current_cluster="${{ vars.MQPT_CLUSTER }}"
-            if [[ "${current_cluster}" == "Dallas_n10" ]]; then
-                next_cluster="Dallas_n11"
-            elif [[ "${current_cluster}" == "Dallas_n11" ]]; then
-                next_cluster="Dallas_n12"
-            elif [[ "${current_cluster}" == "Dallas_n12" ]]; then
-                next_cluster="Dallas_n10"
-            else
-                echo "Error: Invalid cluster name '${current_cluster}'. Expected 'Dallas_n10', 'Dallas_n11', or 'Dallas_n12'."
-                exit 1
-            fi
-            echo "Next cluster: ${next_cluster}"
-            echo "NEXT_CLUSTER=$next_cluster" >> "${GITHUB_ENV}"
+          current_cluster="${{ vars.MQPT_CLUSTER }}"
+          if [[ "${current_cluster}" == "Dallas_n10" ]]; then
+              next_cluster="Dallas_n11"
+          elif [[ "${current_cluster}" == "Dallas_n11" ]]; then
+              next_cluster="Dallas_n12"
+          elif [[ "${current_cluster}" == "Dallas_n12" ]]; then
+              next_cluster="Dallas_n10"
+          else
+              echo "Error: Invalid cluster name '${current_cluster}'. Expected 'Dallas_n10', 'Dallas_n11', or 'Dallas_n12'."
+              exit 1
+          fi
+          echo "Next cluster: ${next_cluster}"
+          echo "NEXT_CLUSTER=$next_cluster" >> "${GITHUB_ENV}"
 
       - name: Update GS_STATE to input value
         uses: mmoyaferrer/set-github-variable@31e0d07964802728d7bf8e09dc45b86ee2c8d5f8 # v1.0.0
