ci: add step to validate if tag exists or not
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/.github/workflows/flow-generate-release-notes.yaml b/.github/workflows/flow-generate-release-notes.yaml
--- a/.github/workflows/flow-generate-release-notes.yaml
+++ b/.github/workflows/flow-generate-release-notes.yaml
@@ -52,6 +52,22 @@ jobs:
           echo "Release identifier is valid: ${release_identifier}"
           echo "release-identifier=${release_identifier}" >> ${GITHUB_OUTPUT}
 
+      - name: Validate Tag Exists
+        run: |
+          tag="v${{ steps.validate.outputs.release-identifier }}"
+
+          echo "Checking if tag ${tag} exists..."
+
+          # Check if the tag exists in the repository
+          git fetch --tags
+
+          if git rev-parse "$tag" >/dev/null 2>&1; then
+            echo "Tag '${tag}' found."
+          else
+            echo "Error: Tag '${tag}' does not exist."
+            exit 1
+          fi
+
       - name: Checkout Code
         id: checkout_code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
