back out more changes
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/.github/workflows/zxc-create-github-release.yaml b/.github/workflows/zxc-create-github-release.yaml
--- a/.github/workflows/zxc-create-github-release.yaml
+++ b/.github/workflows/zxc-create-github-release.yaml
@@ -25,7 +25,7 @@ on:
         description: "Perform Dry Run"
         type: boolean
         required: false
-        default: true
+        default: false
     secrets:
       gh-access-token:
         description: "The GitHub access token used to create the release."
@@ -77,26 +77,18 @@ jobs:
 
       - name: Validate and Correct Release Identifier
         id: validate
-        env:
-          DRY_RUN: ${{ inputs.dry-run }}
         run: |
           release_identifier="${{ steps.extract-version.outputs.version }}"
 
           echo "Input release identifier: '${release_identifier}'"
 
-          # If dry run is enabled, skip validation and use the input as-is. Otherwise, validate the version and clean it if necessary.
-          if [[ $DRY_RUN == "true" ]]; then
-            echo "Dry run mode - skipping validation and using input as-is."
-            release_identifier="${{ inputs.release-version }}"
-          else
-            is_valid=$(semver validate "${release_identifier}")
-            if [[ "$is_valid" != "valid" ]]; then
-              echo "Invalid semantic version: ${release_identifier}"
-              exit 1
-            fi
-            release_identifier="${release_identifier#v}"
+          is_valid=$(semver validate "${release_identifier}")
+          if [[ "$is_valid" != "valid" ]]; then
+            echo "Invalid semantic version: ${release_identifier}"
+            exit 1
           fi
-
+          release_identifier="${release_identifier#v}"
+          
           echo "Release identifier is valid: ${release_identifier}"
           echo "release-identifier=${release_identifier}" >> "${GITHUB_OUTPUT}"
           echo "Validated Input: ${release_identifier}" >> "${GITHUB_STEP_SUMMARY}"
@@ -111,7 +103,7 @@ jobs:
 
       - name: Validate Tag Exists
         run: |
-          tag="${{ steps.validate.outputs.release-identifier }}"
+          tag="${{ steps.extract-version.outputs.version }}"
 
           echo "Checking if tag ${tag} exists..."
 
