test: to check if namespace is already in use
Signed-off-by: Alex Kuzmin <alex.kuzmin@swirldslabs.com>

diff --git a/.github/workflows/zxc-single-day-longevity-test.yaml b/.github/workflows/zxc-single-day-longevity-test.yaml
--- a/.github/workflows/zxc-single-day-longevity-test.yaml
+++ b/.github/workflows/zxc-single-day-longevity-test.yaml
@@ -178,6 +178,18 @@ jobs:
           echo "namespace=${NAMESPACE_PREFIX}${n}" >> "${GITHUB_OUTPUT}"
           echo "namespace=${NAMESPACE_PREFIX}${n}" >> "${GITHUB_STEP_SUMMARY}"
 
+      - name: Check for namespace
+        run: |
+          NETWORK_ID="$(echo "${{ steps.set-namespace.outputs.namespace }}" | perl -pne '~s/^.*[^\d](\d+)$/$1/g')"
+
+          sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | grep -E "solo-.*t-n${NETWORK_ID}"
+          if [ ${?} -eq 0 ]
+          then
+            echo "::error The namespace[s] with NETWORK_ID=${NETWORK_ID} already exist[s]. Please check previous run; remove with 'kubectl delete namespaces <namespace namespace ...>'"
+            exit 13
+          fi
+          echo "DEBUG:"
+          exit 113
       - name: Print parameters
         run: |
           echo "inputs.test-asset=${{ inputs.test-asset }}" | tee -a "${GITHUB_STEP_SUMMARY}" "${{ github.workspace }}"/version_run.txt
@@ -230,11 +242,6 @@ jobs:
           set +x
           set +e
           curdir="$(pwd)"
-          sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | grep "${{ steps.set-namespace.outputs.namespace }}"
-          if [ ${?} -eq 0 ]
-          then
-            sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt delete namespace "${{ steps.set-namespace.outputs.namespace }}"
-          fi
 
           # Create the solo directory
           mkdir -p "${{ github.workspace }}"/solo && cd "${{ github.workspace}}"/solo
