Network experiment
Signed-off-by: Alex Kuzmin <alex.kuzmin@swirldslabs.com>

diff --git a/.github/workflows/zxc-single-day-longevity-test.yaml b/.github/workflows/zxc-single-day-longevity-test.yaml
--- a/.github/workflows/zxc-single-day-longevity-test.yaml
+++ b/.github/workflows/zxc-single-day-longevity-test.yaml
@@ -83,15 +83,29 @@ jobs:
         uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
         with:
           egress-policy: audit
-      - name: Setup Helm
+      - name: Check Network
         shell: bash
         run: |
-          ls -l /home/runner/_work/_tool/helm/
-          echo $PATH
-          sudo ln -s /home/runner/_work/_tool/helm/4.1.1/x64/linux-amd64/helm /usr/bin/helm
-          which helm
-          helm version
-          exit 13
+          echo "started at"
+          date
+          date +%s
+
+          while [ true ]
+          do
+            curl -v https://status.hedera.com/api/v2/summary.json >/tmp/curlstatus$$.log 2>&1
+            grep '< HTTP/2 200' /tmp/curlstatus$$.log >/dev/null
+            if [ $? -ne 0 ]
+            then
+               echo "ERROR: response is not 200"
+               cat /tmp/curlstatus$$.log
+               echo "at "
+               date
+               date +%s
+               exit 13
+            fi
+            sleep 0.5s
+          done
+
       - name: Checkout Code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
