removed simulated HAPI failure
Signed-off-by: Kelly Greco <kelly@swirldslabs.com>

diff --git a/.github/workflows/zxc-execute-hapi-tests.yaml b/.github/workflows/zxc-execute-hapi-tests.yaml
--- a/.github/workflows/zxc-execute-hapi-tests.yaml
+++ b/.github/workflows/zxc-execute-hapi-tests.yaml
@@ -150,10 +150,10 @@ jobs:
           node-version: "${{ inputs.node-version }}"
 
       # TODO: Remove this step after testing infrastructure failure detection
-      - name: Simulated Infrastructure Failure
-        run: |
-          echo "Simulating infrastructure failure for testing"
-          exit 1
+#      - name: Simulated Infrastructure Failure
+#        run: |
+#          echo "Simulating infrastructure failure for testing"
+#          exit 1
 
       - name: HAPI Testing (Misc)
         id: gradle-hapi-misc
