remove simulated failures
Signed-off-by: Kelly Greco <kelly@swirldslabs.com>

diff --git a/.github/workflows/zxc-verify-gradle-build-determinism.yaml b/.github/workflows/zxc-verify-gradle-build-determinism.yaml
--- a/.github/workflows/zxc-verify-gradle-build-determinism.yaml
+++ b/.github/workflows/zxc-verify-gradle-build-determinism.yaml
@@ -74,10 +74,10 @@ jobs:
           gradle-cache-read-only: "false"
 
       # TODO: Remove this step after testing infrastructure failure detection
-      - name: Simulated Infrastructure Failure
-        run: |
-          echo "Simulating infrastructure failure for testing"
-          exit 1
+#      - name: Simulated Infrastructure Failure
+#        run: |
+#          echo "Simulating infrastructure failure for testing"
+#          exit 1
 
       - name: Authenticate to Google Cloud
         id: google-auth
