Update for when we bring in the SDPT from performance-analysis repo
- Validate the tag that's passed in
- Call SDPT
- Tag as sdpt-pass-{build-no}

Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/zxf-single-day-perf-test.yaml b/.github/workflows/zxf-single-day-perf-test.yaml
--- a/.github/workflows/zxf-single-day-perf-test.yaml
+++ b/.github/workflows/zxf-single-day-perf-test.yaml
@@ -1,12 +1,11 @@
 # SPDX-License-Identifier: Apache-2.0
-name: "ZXF: CITR Single Day Performance Test"
+name: "ZXF: [CITR] Single Day Performance Test"
 on:
   workflow_dispatch:
     inputs:
       tag-to-run:
         description: "The tag to run CITR SDPT against"
         required: true
-        default: 'build-00099'
 
 defaults:
   run:
@@ -16,47 +15,75 @@ permissions:
   contents: read
 
 jobs:
-  run-citr-performance-test:
-    name: Run Single Day Performance Test
+  verify-tag:
+    name: Verify Tag
     runs-on: hiero-network-node-linux-medium
+    outputs:
+      build-number: ${{ steps.verify-tag.outputs.build-number }}
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
         with:
           egress-policy: audit
 
-      # Get the `build-XXXXX' tag (latest tag) to run the performance test
-      # use it later as ${{ steps.tag.outputs.tag }}
-      - name: Get Build Tag
-        id: tag
-        run: |
-          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
-            # Triggered by tag push
-            tag_name="${GITHUB_REF#refs/tags/}"
-          else
-            # Triggered by workflow_dispatch
-            tag_name="${{ github.event.inputs.tag-to-run }}"
-          fi
-          echo "Using tag: ${tag_name}"
-          echo "tag_name=${tag_name}" >> "${GITHUB_OUTPUT}"
-
-      # Call the performance workflow with appropriate input version
-      - name: Call CITR Performance Workflow
-        uses: step-security/workflow-dispatch@05938d638f4ddc45d2c59dfd122d3ba247fb7015 # v1.2.6
+      - name: Checkout Consensus Node
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
-          workflow: .github/workflows/performance-CITR.yml
-          repo: swirldslabs/performance-analysis-automation # ensure we are executing in the perf analysis automation repo
-          ref: main # ensure we are always using the workflow definition from the main branch
-          token: ${{ secrets.PERF_ANALYSIS_TOKEN }}
-          inputs: '{
-            "namespace": "Latitude4",
-            "hcn-version": "${{ steps.tag.outputs.tag_name }}",
-            "solo-version": "latest_tested_solo-charts0.59",
-            "nlg-accounts": "100000000",
-            "nlg-time": "330m",
-            "nlg-time3": "2h",
-            "add-app-props": "",
-            "add-settings": "",
-            "crypto-bench-merkle-db-java-args": "-XX:+UseZGC -XX:+ZGenerational -XX:ZAllocationSpikeTolerance=2 -XX:ConcGCThreads=14 -XX:ZMarkStackSpaceLimit=12g -XX:MaxDirectMemorySize=24g -Xmx90g",
-            "crypto-bench-merkle-db-test-params": "-p maxKey=500000000 -p numRecords=100000 -p keySize=24 -p recordSize=1024 -p numFiles=6000"
-          }'
+          ref: ${{ github.event.inputs.tag-to-run }}
+
+      - name: Verify Tag
+        env:
+          PROMOTED_GREP_PATTERN: "build-.{5}" # Pattern to match build tags (e.g., build-12345)
+          CHECK_TAG: "${{ github.event.inputs.tag-to-run }}"
+        run: |
+          # Ensure the tag that we received is a build tag
+          # if the tag is a build tag then we can parse out the build number (the last 5 characters)
+          # return the build tag as an output
+          # if the tag is not a build tag then we will fail the workflow
+          if [[ "${CHECK_TAG}" =~ ${PROMOTED_GREP_PATTERN} ]]; then
+            echo "The tag is a valid build tag."
+            BUILD_NUMBER="${CHECK_TAG: -5}"
+            echo "build-number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
+          else
+            echo "::error title=Invalid Tag::The provided tag (${github.event.inputs.tag-to-run}) is not a valid build tag."
+            exit 1
+          fi
+
+  run-single-day-performance-test:
+    name: Run Single Day Performance Test
+    uses: .github/workflows/zxf-run-single-day-performance-test.yml
+    needs: verify-tag
+    with:
+      namespace: "Latitude4",
+      hcn-version: "${{ github.event.inputs.tag-to-run }}",
+      solo-version: "latest_tested_solo-charts0.59",
+      nlg-accounts: "100000000",
+      nlg-time: "330m",
+      nlg-time3: "2h",
+      add-app-props: "",
+      add-settings: "",
+      crypto-bench-merkle-db-java-args: "-XX:+UseZGC -XX:+ZGenerational -XX:ZAllocationSpikeTolerance=2 -XX:ConcGCThreads=14 -XX:ZMarkStackSpaceLimit=12g -XX:MaxDirectMemorySize=24g -Xmx90g",
+      crypto-bench-merkle-db-test-params: "-p maxKey=500000000 -p numRecords=100000 -p keySize=24 -p recordSize=1024 -p numFiles=6000"
+
+  tag-sdpt-passing:
+    name: Tag SDPT Passing
+    runs-on: hiero-network-node-linux-medium
+    needs:
+      - run-single-day-performance-test
+      - verify-tag
+    if: ${{ needs.run-citr-performance-test.outputs.sdpt-passing == 'true' }}
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
+        with:
+          egress-policy: audit
+
+      - name: Checkout Consensus Node
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ github.event.inputs.tag-to-run }}
+
+      - name: Tag SDPT Passing
+        run: |
+          git tag --annotate "sdpt-pass-${{ jobs.verify-tag.outputs.build-number }}" --message "Single Day Performance Test passed for build-${{ jobs.verify-tag.outputs.build-number }}"
+          git push origin "sdpt-pass-${{ jobs.verify-tag.outputs.build-number }}" --force
